In [20]:
import json
import requests
from pprint import pprint
from time import sleep
import pandas as pd
import numpy as np

url = "https://api.themoviedb.org/3/discover/movie?api_key=947778a6875678206b391f256e04d8a7&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&primary_release_year=2017&vote_count.gte=100&page="
fresponse=[]
json=[]
for i in range (1,19):
    furl=url+"%d"%i
    response = requests.get(furl).json()

    for item in response["results"]:
        fresponse.append(item)

print(len(fresponse))

341

In [25]:
movie_id_list=[]
for i in range (len(fresponse)):
    movie_id_list.append(fresponse[i]["id"])

len(movie_id_list)

341

In [32]:
df = pd.DataFrame({"id":movie_id_list})
df["budget"]=""   
df["genres"]=""     
df["original_title"]=""    
df["popularity"]=""    
df["production_companies"]=""    
df["release_date"]=""    
df["revenue"]=""    
df["runtime"]=""    
df["vote_average"]=""    
df["vote_count"]=""
df["overview"] =""
df.head()

,id,budget,genres,original_title,popularity,production_companies,release_date,revenue,runtime,vote_average,vote_count,overview
0,284053,,,,,,,,,,,
1,181808,,,,,,,,,,,
2,274855,,,,,,,,,,,
3,281338,,,,,,,,,,,
4,263115,,,,,,,,,,,

In [38]:
url=f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=947778a6875678206b391f256e04d8a7&language=en-US"
for index, row in df.iterrows():
    movie_id = row['id']
    
    response = requests.get(url).json()
    df.loc[index, 'budget'] = response['budget']
    df.at[index, 'genres'] = response['genres']
    df.loc[index, 'original_title'] = response['original_title']
    df.loc[index, 'popularity'] = response['popularity']
    df.at[index, 'production_companies'] = response['production_companies']
    df.loc[index, 'release_date'] = response['release_date']
    df.loc[index, 'revenue'] = response['revenue']
    df.loc[index, 'runtime'] = response['runtime']
    df.loc[index, 'vote_average'] = response['vote_average']
    df.loc[index, 'vote_count'] = response['vote_count']
    df.loc[index, 'overview'] = response['overview']
    sleep(0.3)

In [40]:
df.to_csv("2017_movie_info.csv", index=False, header=True)
df

,id,budget,genres,original_title,popularity,production_companies,release_date,revenue,runtime,vote_average,vote_count,overview
0,284053,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
1,181808,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
2,274855,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
3,281338,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
4,263115,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
5,297762,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
6,335984,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
7,315635,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
8,283995,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
9,141052,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
10,354912,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
11,166426,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
12,399055,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
13,337339,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
14,406990,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
15,341174,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
16,455656,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
17,347882,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
18,316029,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
19,381288,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
20,343668,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
21,47971,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
22,321612,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
23,374720,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
24,126889,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
25,340027,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
26,419430,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
27,339964,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
28,425336,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
29,339403,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
...,...,...,...,...,...,...,...,...,...,...,...,...
311,432618,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
312,411873,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
313,433251,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
314,437739,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
315,449415,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
316,426962,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
317,437425,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
318,396493,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
319,425591,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
320,459950,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
321,430528,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
322,398924,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
323,419511,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
324,420950,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
325,398920,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
326,408381,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
327,425980,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
328,426285,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
329,411019,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
330,406385,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
331,431937,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
332,439584,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
333,435707,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
334,440708,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
335,469019,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
336,445793,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
337,433422,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
338,271404,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
339,456508,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...
340,441614,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,108.359,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,6997,Thor is on the other side of the universe and ...