In [1]:
#import dependencies
import pandas as pd
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
analyzer = SentimentIntensityAnalyzer()
import json
import statistics
import matplotlib.pyplot as plt
import numpy as np
import requests
from pprint import pprint
from time import sleep

In [5]:
# url = "https://api.themoviedb.org/3/discover/movie?api_key=947778a6875678206b391f256e04d8a7&language=en-US&sort_by=popularity.desc&include_adult=false&include_video=false&primary_release_year=2017&vote_count.gte=100&page="
# fresponse=[]
# json=[]
# for i in range (1,19):
#     furl=url+"%d"%i
#     response = requests.get(furl).json()

#     for item in response["results"]:
#         fresponse.append(item)

# # print(len(fresponse))

# movie_id_list=[]
# for i in range (len(fresponse)):
#     movie_id_list.append(fresponse[i]["id"])

# # len(movie_id_list)

# df = pd.DataFrame({"id":movie_id_list})
# df["budget"]=""   
# df["genres"]=""     
# df["original_title"]=""    
# df["popularity"]=""    
# df["production_companies"]=""    
# df["release_date"]=""    
# df["revenue"]=""    
# df["runtime"]=""    
# df["vote_average"]=""    
# df["vote_count"]=""
# df["overview"] =""
# # df.head()

# for index, row in df.iterrows():
#     movie_id = row['id']
#     url=f"https://api.themoviedb.org/3/movie/{movie_id}?api_key=947778a6875678206b391f256e04d8a7&language=en-US"
#     response = requests.get(url).json()
#     df.loc[index, 'budget'] = response['budget']
#     df.at[index, 'genres'] = response['genres']
#     df.loc[index, 'original_title'] = response['original_title']
#     df.loc[index, 'popularity'] = response['popularity']
#     df.at[index, 'production_companies'] = response['production_companies']
#     df.loc[index, 'release_date'] = response['release_date']
#     df.loc[index, 'revenue'] = response['revenue']
#     df.loc[index, 'runtime'] = response['runtime']
#     df.loc[index, 'vote_average'] = response['vote_average']
#     df.loc[index, 'vote_count'] = response['vote_count']
#     df.loc[index, 'overview'] = response['overview']
#     sleep(0.3)
    
# df.to_csv("2017_movie_info.csv", index=False, header=True)
# df.head()

,id,budget,genres,original_title,popularity,production_companies,release_date,revenue,runtime,vote_average,vote_count,overview
0,284053,180000000,"[{'id': 28, 'name': 'Action'}, {'id': 12, 'nam...",Thor: Ragnarok,109.022,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130,7.5,7007,Thor is on the other side of the universe and ...
1,274855,120000000,"[{'id': 28, 'name': 'Action'}, {'id': 878, 'na...",Geostorm,53.5538,"[{'id': 101832, 'logo_path': '/vO7CKIeogFxphT1...",2017-10-13,221600160,109,5.8,1490,After an unprecedented series of natural disas...
2,181808,200000000,"[{'id': 14, 'name': 'Fantasy'}, {'id': 12, 'na...",Star Wars: The Last Jedi,52.7981,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...",2017-12-13,1332459537,152,7.1,5844,Rey develops her newly discovered abilities wi...
3,281338,150000000,"[{'id': 18, 'name': 'Drama'}, {'id': 878, 'nam...",War for the Planet of the Apes,51.3844,"[{'id': 22213, 'logo_path': '/qx9K6bFWJupwde0x...",2017-07-11,488533726,140,6.9,3946,Caesar and his apes are forced into a deadly c...
4,263115,97000000,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",Logan,44.214,"[{'id': 431, 'logo_path': None, 'name': 'The D...",2017-02-28,616801808,137,7.7,9453,"In the near future, a weary Logan cares for an..."

In [68]:
api_df = pd.read_csv("2017_movie_info.csv")
api_df = pd.DataFrame(api_df)

# merged_df = string_lists.append(api_df)
for row in api_df["genres"]:
    
    jrow=row.replace("'", '\"')
#     print(row)
api_df["genres"] = jrow    
api_df.head()
# unique_genres  = [w.replace(" ", "_") for w in unique_genres]

,id,budget,genres,original_title,popularity,production_companies,release_date,revenue,runtime,vote_average,vote_count,overview
0,284053,180000000,"[{""id"": 10749, ""name"": ""Romance""}]",Thor: Ragnarok,109.021591,"[{'id': 420, 'logo_path': '/hUzeosd33nzE5MCNsZ...",2017-10-25,853977000,130.0,7.5,7007,Thor is on the other side of the universe and ...
1,274855,120000000,"[{""id"": 10749, ""name"": ""Romance""}]",Geostorm,53.553775,"[{'id': 101832, 'logo_path': '/vO7CKIeogFxphT1...",2017-10-13,221600160,109.0,5.8,1490,After an unprecedented series of natural disas...
2,181808,200000000,"[{""id"": 10749, ""name"": ""Romance""}]",Star Wars: The Last Jedi,52.798146,"[{'id': 1, 'logo_path': '/o86DbpburjxrqAzEDhXZ...",2017-12-13,1332459537,152.0,7.1,5844,Rey develops her newly discovered abilities wi...
3,281338,150000000,"[{""id"": 10749, ""name"": ""Romance""}]",War for the Planet of the Apes,51.384361,"[{'id': 22213, 'logo_path': '/qx9K6bFWJupwde0x...",2017-07-11,488533726,140.0,6.9,3946,Caesar and his apes are forced into a deadly c...
4,263115,97000000,"[{""id"": 10749, ""name"": ""Romance""}]",Logan,44.214025,"[{'id': 431, 'logo_path': None, 'name': ""The D...",2017-02-28,616801808,137.0,7.7,9453,"In the near future, a weary Logan cares for an..."

In [53]:
#temp_genres.replace('\'', '"')


test = '\"'
print(test)

"

In [12]:
string_lists = pd.read_csv("tmdb_5000_movies.csv")
string_lists = pd.DataFrame(string_lists)

string_lists["overview"][0].dtypes

AttributeError: 'str' object has no attribute 'dtypes'

In [70]:
#read the csv datafile and convert it to dataframe
string_lists = pd.read_csv("tmdb_5000_movies.csv")
string_lists = pd.DataFrame(string_lists)
string_lists1 = string_lists[["id", "budget", "genres", "original_title", "popularity", "production_companies", "release_date"
                             , "revenue", "runtime", "vote_average", "vote_count", "overview"]]

api_df = pd.read_csv("2017_movie_info.csv")
api_df = pd.DataFrame(api_df)

merged_df = string_lists1.append(api_df)


#clean the data
#remove data with not enough votes, as weel as empty cells in columns that are needed
clean_df = api_df.loc[string_lists["vote_count"]>100]
clean_df = clean_df.loc[clean_df["production_companies"] != "[]"]
clean_df = clean_df.loc[clean_df["genres"] != "[]"]
#remove unnedded columns and reset the index
clean_df1 = clean_df[["budget", "genres", "original_title", "popularity", "production_companies",
                      "release_date", "revenue", "runtime", "vote_average", "vote_count", "overview"]]
clean_df1 = clean_df1.reset_index(drop=True)

#create a list to add the coumpound polarity scores and add the completed list as a new column to the dataframe
compound = []

#go through each row and run vader analysis on each
for index, row in clean_df1.iterrows():
#     #append to a variable
#     results = analyzer.polarity_scores(clean_df1["overview"][index])
#     #take the compund score and set to a variable
#     comp = results["compound"]
#     #append the compund score variable to the compound list
#     compund.append(comp)
    try:
        results = analyzer.polarity_scores(clean_df["overview"][index])
        comp = results["compound"]  
    except:
        comp=None
    compound.append(comp)


#add the compound column to the dataframe    
clean_df1["compound_score"] = compound   

# clean_df1.head()

# print(len(clean_df1))
# clean_df1 = pd.DataFrame(clean_df1)
# merged_df

In [71]:
#create of list of genres, first by creating a blank list
unique_genres = []

#then bygo through each row in the genres column and
for row in clean_df1["genres"]:
    #load it into a varable using json.loads
    jdata = json.loads(row)
    #go through each dictionary in in the variable and
    for d in jdata:
        #check to see if the name has been placed into the unique_genres list yet
        if d["name"] not in unique_genres:
            #if not, append it to the list
            unique_genres.append(d['name'])

#Remove spaces from the genres            
unique_genres  = [w.replace(" ", "_") for w in unique_genres]            
#display the list so each genre can be seen            
unique_genres

JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 3 (char 2)

In [4]:
#Create a data frame for each genre to compare with each other

#Createan empty list for each genre programmatically
for n in unique_genres:
    globals()[n] = []


#go through each row in the cleaned dataframe and
for index,row in clean_df1.iterrows():
    #use json.loads on the genres column at the position of the current index 
    jdata = json.loads(clean_df1["genres"][index])
    
    #for each dictionary in the created variable, check which genres appear and append to the proper list
    #DO NOT USE elif, to check if a row belongs in multiple lists use a seperate if statement for each list
    for d in jdata:

        if d["name"] == "Action":
            Action.append(row)
            
        if d["name"] == "Adventure":
            Adventure.append(row) 
        
        if d["name"] == "Fantasy":
            Fantasy.append(row)  
            
        if d["name"] == "Science Fiction":
            Science_Fiction.append(row)  
            
        if d["name"] == "Crime":
            Crime.append(row)  
            
        if d["name"] == "Drama":
            Drama.append(row)  
            
        if d["name"] == "Thriller":
            Thriller.append(row)  
            
        if d["name"] == "Animation":
            Animation.append(row)  
        
        if d["name"] == "Family":
            Family.append(row)  
        
        if d["name"] == "Western":
            Western.append(row)  
            
        if d["name"] == "Comedy":
            Comedy.append(row)  
            
        if d["name"] == "Romance":
            Romance.append(row)  
            
        if d["name"] == "Horror":
            Horror.append(row)  
         
        if d["name"] == "Mystery":
            Mystery.append(row)  
            
        if d["name"] == "History":
            History.append(row)  
            
        if d["name"] == "War":
            War.append(row)  
            
        if d["name"] == "Music":
            Music.append(row)  
            
        if d["name"] == "Documentary":
            Documentary.append(row)  
            
        if d["name"] == "TV Movie":
            TV_Movie.append(row)      
        
#convert them all to dataframes
Action_df = pd.DataFrame(Action)
Adventure_df = pd.DataFrame(Adventure)
Fantasy_df = pd.DataFrame(Fantasy)
Science_Fiction_df = pd.DataFrame(Science_Fiction)
Crime_df = pd.DataFrame(Crime)
Drama_df = pd.DataFrame(Drama)
Thriller_df = pd.DataFrame(Thriller)
Animation_df = pd.DataFrame(Animation)
Family_df = pd.DataFrame(Family)
Western_df = pd.DataFrame(Western)
Comedy_df = pd.DataFrame(Comedy)
Romance_df = pd.DataFrame(Romance)
Horror_df = pd.DataFrame(Horror)
Mystery_df = pd.DataFrame(Mystery)
History_df = pd.DataFrame(History)
War_df = pd.DataFrame(War)
Music_df = pd.DataFrame(Music)
Documentary_df = pd.DataFrame(Documentary)
TV_Movie_df = pd.DataFrame(TV_Movie)


##The code under here works to be used elsewhere
# sums = []
# for index,row in Adventure_df.iterrows():
#     sums.append(Adventure_df["vote_average"][index])
# averages = (sum(sums)/len(sums)).round(2)    
# averages
##The code above works to be used elsewhere

In [5]:
len(Science_Fiction_df)

441